# Generated by Django 5.2.3 on 2025-07-02 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField()),
                ('went_to_gym', models.BooleanField()),
                ('workout_details', models.TextField(blank=True)),
                ('calories_burned', models.IntegerField(default=0)),
                ('free_time_minutes', models.IntegerField(blank=True, null=True)),
                ('suggested_exercises', models.TextField(blank=True)),
            ],
        ),
    ]
