# Generated by Django 5.2.3 on 2025-07-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='milestone_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
